setwd('/home/tuomas/R/Projects/DATA.ML420/datasets')
data = read.table('disease.txt', head=T)

# b)
library(spatstat)
plot(data$x, data$y)
data.points = ppp(data$x, data$y, c(0,33),c(0,33) ) #cbind(data$x, data$y)

# Quadrat test
qcount = quadratcount(data.points, nx=7, ny=7)
plot(data.points)
plot(qcount, add=TRUE)

qtest = quadrat.test(data.points, nx=7, ny=7)
qtest
# X2 = 324.62, df = 48, p-value < 2.2e-16
# Since the p-value is < 2.2e-16 we can say that the data is not generated by 
# completely random spatial process.

# G-function
plot(Gest(data.points))
r = seq(0,1.2, by=0.005)
env.g = envelope(data.points, fun=Gest, r=r, nrank=2, nsim=99)
plot(env.g)
# Since the observed G-function values are clearly out of the bounds of the envelope
# (at above), we can say that the point pattern data is rather aggregated than random

# Ripley's K function
plot(Kest(data.points))
env.k = envelope(data.points, fun=Kest, r=r, nrank=2, nsim=99)
plot(env.k)
# Similarly as before, the observed K-function values are clearly above the envelope. This 
# suggest that the point pattern is aggregated.

# c)
library(splancs)
# HPP
hpp.fit = ppm(data.points, ~1)
AIC(hpp.fit)
# [1] 1158.453
plot(envelope(hpp.fit, Kest, nsim = 39, global = TRUE))

# IPP
ipp.fit = ppm(data.points, ~x+y)
AIC(ipp.fit)
# [1] 1116.621
plot(envelope(ipp.fit, Kest, nsim = 39, global = TRUE))
# Based on the AIC's, IPP fits better.
anova(hpp.fit, ipp.fit, test='Chi')
# This suggest IPP as well.

# PCP
pcp.fit = kppm(data.points, method ='mincon')
plot(envelope(pcp.fit, Kest, nsim = 39, global = TRUE))
# However, since the data looks clearly clustered, I tested visually that the PCP process
# is closest to the theoretical K-function (and inside the envelope). Hence I think that 
# the PCP process fitted best to the observed pattern.

dg.test(hpp.fit)
dg.test(ipp.fit)
dg.test(pcp.fit)
